### ISSUE TITLE
[Question] Is there any issue when uploading to Chrome web store?

### ISSUE THREAD

**Issue by piavgh** [kryptokinght/react-extension-boilerplate#17]
Hi @kryptokinght ,

Thank you for making this repository. It's the most recent updated boilerplate for Chrome extension that I found on Github.

One thing that makes me concern is that: is there any issue when uploading to Chrome web store (Contains minified or obfuscated code rejection from Google)? Did you upload any extension to the Chrome web store successfully using this repository before?

I just don't want to have any surprises.

Thank you very much.

**Comment by kryptokinght** [comment]
I haven't tried uploading an extension to the Chrome web store created through this boilerplate. There are still a few bugs left to be solved and also it hasn't been tested yet. So I suggest you to not use this boilerplate in the meantime. I will soon be updating this repo and will also add a CLI tool just like create-react-app, so do keep a watch!

**Comment by piavgh** [comment]
Thank you 👍

**Comment by msuhov** [comment]
HI @kryptokinght 
Do you have any updates on that topic?

**Comment by sam-frampton** [comment]
Hi @kryptokinght - thanks for the boilerplate repository. Have you since tested the repo and upload a chrome app to the store?

Similar to the first comment I'm trying to avoid any surprises. 

Thanks

**Comment by Toumash** [comment]
Any update here?

**Comment by Enkey** [comment]
Hi @Toumash 

I've published very simple extension in terms of permissions(only for Google and firebase domains). It works fine, no issue on my side

Many thanks to @kryptokinght

**Comment by Toumash** [comment]
My project that im developing now for a full year is working just fine. Issue should be closed.
